remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Eric's GitHub Pages Test Site
description: Testing GitHub Pages, Jekyll themes, and static website hosting.
show_downloads: false